### ISSUE TITLE
Broken highlighting of dash-separated tags

### ISSUE THREAD

**Issue by zezic** [digitaltoad/vim-pug#115]
Dash-separated tags are often case in Vue components, but vim-pug detects `-` as a `pugJavascriptChar`.

![screenshot at 2019-02-18 03-03-34](https://user-images.githubusercontent.com/1945127/52921604-f3e41e80-3329-11e9-8dc1-c8f1541a676f.png)

**Comment by char101** [comment]
A possible fix is to replace [pug.vim#L30](https://github.com/digitaltoad/vim-pug/blob/master/syntax/pug.vim#L30) with:

```viml
syn region  pugJavascript matchgroup=pugJavascriptChar start="\(^\|\s\)\@<=-" skip=",\s*$" end="$" contained contains=@htmlJavascript keepend
```

It checks that the javascript marker (`-`) is at the beginning or after a whitespace.

**Comment by zezic** [comment]
@char101 That's nice! Do you mind creating a pull request for this?

**Comment by char101** [comment]
@zezic If this solves the problem I prefer @acidjazz change it directly. For tiny change like this, copy-paste still rules. 😬

**Comment by acidjazz** [comment]
@zezic @char101 i've gone ahead and submitted the change to master, please confirm it works and i'll go ahead and close this, thanks everyone!

**Comment by zezic** [comment]
Thank you, @acidjazz! I just tested it and it seems to work well for me.
