### ISSUE TITLE
Will it work woth Vim-Plug?

### ISSUE THREAD

**Issue by annata83** [digitaltoad/vim-pug#120]
Hello;  there is anyway to install it thru vim-Plug plugin manager?

**Comment by acidjazz** [comment]
@annata83 just add this to your ~/.vimrc

```vim
Plug 'digitaltoad/vim-pug'
```

then open vim and run :!PlugInstall

**Comment by annata83** [comment]
Hello @acidjazz, Thanks for your answer; I actually ask to make sure first that it was supported because I did installed yesterday but it's not working,  would you walk me thru a debug process?
NVIM v0.3.8
[vimrc.txt](https://github.com/digitaltoad/vim-pug/files/3399847/vimrc.txt)

**Comment by acidjazz** [comment]
@annata83 ah NVIM, i haven't exactly tested it in that yet, i mainly use MacVIM.  I'll check that this out when i get time.

**Comment by annata83** [comment]
@acidjazz Alright, I also have vim 8.1 installed with the same results:
![pic-selected-190717-0233-49](https://user-images.githubusercontent.com/18301363/61349680-54c14580-a83b-11e9-9933-07b495d6977c.png)

**Comment by annata83** [comment]
Hey There... Any suggestion on how to go about debugging this?

**Comment by acidjazz** [comment]
@annata83 sorry, so is that screenshot what I'm seeing in a `.pug` file? or w/in a template in a `.vue` file?

**Comment by annata83** [comment]
@acidjazz I am very sorry to say that all this was caused because of the theme I was using...
I do apologize for bothering you.
