### ISSUE TITLE
vim-jade doesn't auto-detect jade filetype on MacVim

### ISSUE THREAD

**Issue by sahat** [digitaltoad/vim-pug#25]
I am using the latest version of vim-jade and MacVim and for some reason the plugin does not syntax highlight automatically jade files.

Plugin is installed correctly via Vundle. I don't believe my .vimrc is the cause. You can take a look at it here: https://github.com/sahat/dotfiles/blob/master/.vimrc

Manually setting :setfiletype jade does the trick for that one particular file. If I open another jade file via CTRL+P I have to :setfiletype jade again.

**Comment by nicksparks** [comment]
i my case it was need to change "for pug" instead of "for jade" 
plug "digitaltoad/vim-jade" {for: pug}
 in .vimrc 

i use vundle
