### ISSUE TITLE
Slow to open Jade files

### ISSUE THREAD

**Issue by steadystatic** [digitaltoad/vim-pug#54]
I'm on Vim 7.4 – for some reason it can take anywhere from 5 to 20 seconds to open some Jade files. This is not a super great way of showing the issue but been testing with this file from Jade's official examples:
﻿
https://github.com/jadejs/jade/blob/master/examples/layout.jade

and just running them with unix time command and hitting Shift ZZ as fast as I can to close vim and track how long it took:

/usr/local/bin/vim .//examples/layout.jade 17.07s user 0.25s system 95% cpu 18.193 total

Any ideas? I'm going line by line through my vimrc and can't seem to stop it.
﻿﻿

**Comment by ot-brett-jones** [comment]
@steadystatic thanks. That was my issue as well. I had an issue opening less and jade files and that was the cause of both

**Comment by brettof86** [comment]
@steadystatic thanks. That was my issue as well. I had an issue opening less and jade files and that was the cause of both
