### ISSUE TITLE
Add support for for gq on plain text (|)

### ISSUE THREAD

**Issue by moll** [digitaltoad/vim-pug#70]
Hey,

Using `gq` to reformat plain text results in the pipe character remaining on the joined line.
In other words, running `gq` on the following lines should break lines at column whatever-is-configured and prefixed with pipes.
```jade
| Very long line Very long line Very long line Very long line Very long line Very long line Very long line Very long line
| Very long line Very long line Very long line Very long line Very long line Very long line Very long line Very long line
```

At the moment no pipe-action:
```jade
| Very long line Very long line Very long line Very long line Very long line
Very long line Very long line Very long line | Very long line Very long line
Very long line Very long line Very long line Very long line Very long line
Very long line
```

Cheers

**Comment by moll** [comment]
Debugged this and it seems it can be solved by adding the pipe character to Vim's `&comments`. I'm not sure what other side-effects that has yet though. Doesn't highlight incorrectly at least.

**Comment by digitaltoad** [comment]
I'm not real fond of adding this to comments but I'm open to suggestions or the pros and cons of doing it that way. I feel like any side-effects to the comment option will not be immediately apparent.

**Comment by moll** [comment]
I set it for myself and it fixed the issue. Bump this issue in a month or so and I can tell if it caused something bad. :)

**Comment by digitaltoad** [comment]
Will do



—
Josh

**Comment by digitaltoad** [comment]
How has this worked for you?

**Comment by moll** [comment]
So far so good. :)
