### ISSUE TITLE
problem in syntax highlighting for inline HTML links

### ISSUE THREAD

**Issue by boompig** [digitaltoad/vim-pug#77]
See screenshot

<img width="1227" alt="screen shot 2015-11-24 at 1 17 01 pm" src="https://cloud.githubusercontent.com/assets/2791268/11376388/704903de-92ae-11e5-8d0a-9c3876a12d6f.png">

**Comment by digitaltoad** [comment]
I'll take a look at this. I wasn't aware until now that inline html was allowed in Jade.
