### ISSUE TITLE
Very slow with any javascript syntax plugin

### ISSUE THREAD

**Issue by KabbAmine** [digitaltoad/vim-pug#80]
Most of the times its very slow to move in a jade file, #33 #54 #67 

The culprit is the [javascript highlighting in each parenthesis block](https://github.com/digitaltoad/vim-jade/blob/master/syntax/jade.vim#L26).
Disable the javascript syntax file each time is not an option.

It would be more than great to provide in your plugin an option (global or buffer-local) to enable/disable the related part above (e.g `b:jade_js_syntax`).

**Comment by digitaltoad** [comment]
Is this still the case with other js syntax highlighters? I noticed the problem when using the particular one noted.

**Comment by KabbAmine** [comment]
Yes, with [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) or [othree/yajs.vim](https://github.com/othree/yajs.vim) (I'm using the 2nd one), it is slow.
Disabling it make it work normally.

I've tested with a clean vimrc with only vim-jade and yajs enabled, and same problem.

*Not related with the issue, but I'm using vim-jade shipped with [vim-polyglot](https://github.com/sheerun/vim-polyglot).*

**Comment by digitaltoad** [comment]
Ok I can see the slight lag when I compare with and without. I'll take a look at it and see what I can come up with.

**Comment by KabbAmine** [comment]
Great, we'll wait for a fix then :smiley:

**Comment by fidelab** [comment]
Any update on this? Big pug / jade files sometimes even make vim crash.

Thanks!

**Comment by digitaltoad** [comment]
No sorry. I haven't had a ton of time to look at this. I'm actually looking for a new maintainer for the project. I just don't use Pug and haven't stayed up to date with the changing syntax.

**Comment by kevcenteno** [comment]
@fidelab @KabbAmine Do y'all mind trying out my fix for this issue?  https://github.com/digitaltoad/vim-pug/pull/102

**Comment by digitaltoad** [comment]
@kevcenteno I'll check it out today.

**Comment by smarquez1** [comment]
@kevcenteno just tested your branch and it fixes the issue. Thanks!

**Comment by KabbAmine** [comment]
LGTM also :+1: 
I think that the issue can be closed now.

**Comment by acidjazz** [comment]
thanks @smarquez1 and @KabbAmine !
