### ISSUE TITLE
HTML5 support

### ISSUE THREAD

**Issue by gorilonmax** [digitaltoad/vim-pug#83]
Hi folks!

First of all, I want to tank you for your job on this vim-pug plugin, it's been very helpful.
I'm wondering if you are considering adding support for HTML5 tags; I've been coding some stuff and had problems on correctly highlighting some tags, such as `header` `main` `footer`.

Thanks again!

**Comment by digitaltoad** [comment]
This is all supported as long as you have [html5.vim](/othree/html5.vim) installed.
