### ISSUE TITLE
Syntax highlighting when adding markdown code in .jade/.pug file.

### ISSUE THREAD

**Issue by maotora** [digitaltoad/vim-pug#84]
Hello, Thank you for this plugin.

There is a problem in syntax highlighting when you add a markdown code in .jade file with `:marked` or `:markdown` sign.

The thing is every code afterwards gets to be (no matter it's jade - or whatever language compatible to jade)
never really gets highlighted as before. Everything gets to be markdown highlighted and that's plain gold(color) for me.

I also made this issue here [stackoverflow](http://stackoverflow.com/questions/36021004/jade-syntax-highlighting-wont-work-after-inserting-markdown-code-in-vim-editor) so you can take a look at the colors.

Thank you.

**Comment by digitaltoad** [comment]
I'm not able to reproduce right now. What does your config look like?

**Comment by maotora** [comment]
Here is a link to my .vimrc [link](https://github.com/maotora/my-dots/blob/master/.vimrc) i hope that's what you meant by `What does your config look like?`

**Comment by digitaltoad** [comment]
Sorry it has taken so long to get back to you on this. I know you said in the SO question that you have learned to live with it. I do suspect that it is another plugin creating a sort of conflict here. A way to make it easier is to use something like https://github.com/Shougo/neobundle.vim and then enable plugins until you find the one that is causing the conflict. This would also help me to figure out if it is something in `vim-pug` that needs to be changed or the actual fault of another plugin.
