### ISSUE TITLE
Word jumps with dash ('-') symbol

### ISSUE THREAD

**Issue by lyutkin** [digitaltoad/vim-pug#85]
When I jump on words with default `w` key, `vim-pug` doesn't honour `-` divider in long WORDS. For example, I got this:
`.menu-list__item-link`
With no` vim-pug` loaded I go just fine with `w` key in such order:` . m - l` (then next WORD).
With active `vim-pug` behavior of `w` jumps is different: `. m` (then next WORD). Even though `-` is present in `iskeyword` variable (tested with `:verbose set iskeyword?` command), I'm not able to navigate normally. Same thing with `_` symbol, it is ignored in words navigation.

I have this issue with `gVim 7.4` on `Windows 7 x64`, `_vimrc` is empty, except of `vim-pug` loaded with `vim-plug` plugin manager.

**Comment by digitaltoad** [comment]
Right now this is by design. I'm willing to hear arguments against this, but for now I'm going to close as it seems to be more common if the syntax allows for `-` and `_` in keywords.
