### ISSUE TITLE
Syntax highlight not working

### ISSUE THREAD

**Issue by thifranc** [digitaltoad/vim-pug#90]
Hi,
I can't get my jade files highlighted : 
My vimrc
```
:set nu
:syntax on
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'digitaltoad/vim-pug'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" disable arrows
nnoremap <up>    <nop>
nnoremap <down>  <nop>
nnoremap <left>  <nop>
nnoremap <right> <nop>
inoremap <up>    <nop>
inoremap <down>  <nop>
inoremap <left>  <nop>
inoremap <right> <nop>
```
I've run :PluginInstall and vim was done without any harm
I've tried with .jade , .html and .pug files and none of them would highlight my jade code

**Comment by scurlyhair** [comment]
@thifranc 
To fix it you should do these things below in your `.vimrc`:
1. disable the filetype before vundle with `filetype off`;
2. enable the filetype below this line `call vundle#end()`
You'd better have a look at [this issue](https://github.com/digitaltoad/vim-pug/issues/60).

**Comment by thifranc** [comment]
Thanks a lot, I had managed to fix myself but those lines were exactly the ones I had added to fix vim !
