### ISSUE TITLE
Custom components highlighted as javascript

### ISSUE THREAD

**Issue by jacoborus** [digitaltoad/vim-pug#92]
Custom HTML5 component tag names should be composed by 2 or more words separated by dashes, vim-plug is highlighting the second part of the name as `pugJavascript` instead as `pugTag`.

Example:

```html
<custom-tag>hello</custom-tag>
```
in Pug:

```pug
custom-tag hello
```
Here vim-pug highlights everything as javascript from the dash

**Comment by kostacoffee** [comment]
I found this problem to be solved if you have an html syntax file that supports custom components. There is progress with this one:
https://github.com/othree/html5.vim/

There is a merge request (shameless plug - my merge request) with some changes that should fix this.

**Comment by jacoborus** [comment]
Ok, I tried your 2 repos (vim-pug and html5) and that solves partially the problem, it is not perfect, but now it pretty usable. Thanks!

I am still facing problems with the dashes in html attributes and also with the use of composed attribute names with words like `if` (`v-if` attribute for vue.js) or attibutes that start with colons (variable attributes for vue.js), but I believe that is matter for a different issue.

**Comment by digitaltoad** [comment]
The Vue specific syntax is probably not a good fit for core unless Pug is really popular with the Vue community. Marking as closed since the issue for the most part is fixed by using a html5 highlighter.
