### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by digitaltoad** [digitaltoad/vim-pug#99]
It has been a long time since I have used Jade/Pug and I have not been keeping up with the changes to the syntax. That said, this project would benefit from a maintainer that is actually using the syntax and is willing to keep up with the changes.

**Comment by acidjazz** [comment]
I can take this over, I love and use this constantly

**Comment by klaplong** [comment]
So, when can we expect some maintenance to happen then?

**Comment by acidjazz** [comment]
@klaplong was there something in particular you were looking for?

**Comment by klaplong** [comment]
@acidjazz Since this issue was opened over a year ago, same as the latest commit, I was wondering whether it was worth it to open a new issue anyway. If the transfer was completed, maybe close this issue?
